name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy app to github pages
    runs-on: ubuntu-latest
    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        env:
          VUE_APP_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        run: |
          git config --global user.name 'benoitdemaegdt'
          git config --global user.email 'benoit.demaegdt@gmail.com'
          git checkout --orphan gh-pages
          npm run build
          git --work-tree dist add --all
          git --work-tree dist commit -m 'deploy'
          git push origin HEAD:gh-pages --force
          rm -r dist
          git checkout -f master
          git branch -D gh-pages